/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MerchantProyect;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santiago
 */
public class frm_Cocina extends javax.swing.JFrame {

    /**
     * Creates new form frm_Cocina
     */
    DefaultTableModel cocina; //El Table Model de la tabla cocina
    ColorearFilas colorfilas = new ColorearFilas(); // Llamada del metodo colorfilas desde la clase ColorearFilas
    
    
    public frm_Cocina() {
        initComponents();
        this.cocina = (DefaultTableModel) tablacocina.getModel();
        Mostrardatos();
        btn_Regresar.hide();
    }

    public void RefrescarTabla(){
        //Funcion para refrescar la tabla reseteando los conteos y revalidando la tabla.
        cocina.setColumnCount(0);
        cocina.setRowCount(0);
        tablacocina.revalidate();
    }
    public final void Mostrardatos(){
        //Funcion que llena la tabla cocina.
        MyConnection cc=new MyConnection();
        Connection cn=MyConnection.getConnection();
        RefrescarTabla();
        cocina.addColumn("ID");
        cocina.addColumn("Producto");
        cocina.addColumn("Cantidad");
        cocina.addColumn("Estado");
        tablacocina.setModel(cocina);
        
        String sql="SELECT IdProducto, Producto, Cantidad FROM Producto";
 
            String []datos=new String [3];
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                        datos[2]=rs.getString(3);
 
            cocina.addRow(datos);
        }
            tablacocina.setModel(cocina);
        }catch(SQLException ex){
            Logger.getLogger(frm_Productos.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb_Panel = new javax.swing.JTabbedPane();
        tb_1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacocina = new javax.swing.JTable();
        tb_2 = new javax.swing.JPanel();
        tb_3 = new javax.swing.JPanel();
        tb_4 = new javax.swing.JPanel();
        btn_Preprar = new javax.swing.JButton();
        btn_Listo = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        lbl_Bienvenido = new javax.swing.JLabel();
        lbl_Mensaje = new javax.swing.JLabel();
        btn_Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Merchant Cocina");
        setName("Cocina"); // NOI18N

        tablacocina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacocina.setName("Producto"); // NOI18N
        tablacocina.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablacocina);

        javax.swing.GroupLayout tb_1Layout = new javax.swing.GroupLayout(tb_1);
        tb_1.setLayout(tb_1Layout);
        tb_1Layout.setHorizontalGroup(
            tb_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tb_1Layout.setVerticalGroup(
            tb_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        tb_Panel.addTab("Bebidas", tb_1);

        javax.swing.GroupLayout tb_2Layout = new javax.swing.GroupLayout(tb_2);
        tb_2.setLayout(tb_2Layout);
        tb_2Layout.setHorizontalGroup(
            tb_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tb_2Layout.setVerticalGroup(
            tb_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Aperitivos", tb_2);

        javax.swing.GroupLayout tb_3Layout = new javax.swing.GroupLayout(tb_3);
        tb_3.setLayout(tb_3Layout);
        tb_3Layout.setHorizontalGroup(
            tb_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tb_3Layout.setVerticalGroup(
            tb_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Comidas", tb_3);

        tb_4.setToolTipText("");

        javax.swing.GroupLayout tb_4Layout = new javax.swing.GroupLayout(tb_4);
        tb_4.setLayout(tb_4Layout);
        tb_4Layout.setHorizontalGroup(
            tb_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        tb_4Layout.setVerticalGroup(
            tb_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Postres", null, tb_4, "");

        btn_Preprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/clock_64.png"))); // NOI18N
        btn_Preprar.setMnemonic('P');
        btn_Preprar.setToolTipText("Preparacion");
        btn_Preprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreprarActionPerformed(evt);
            }
        });

        btn_Listo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/tick_64.png"))); // NOI18N
        btn_Listo.setMnemonic('L');
        btn_Listo.setToolTipText("Listo");
        btn_Listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListoActionPerformed(evt);
            }
        });

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/user_64.png"))); // NOI18N
        btn_Salir.setMnemonic('S');
        btn_Salir.setToolTipText("Desconectar");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/delete_64.png"))); // NOI18N
        btn_Cancelar.setMnemonic('C');
        btn_Cancelar.setToolTipText("Cambiar o Borrar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        lbl_Bienvenido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Bienvenido.setText("Bienvenido:");

        lbl_Mensaje.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Mensaje.setForeground(new java.awt.Color(51, 51, 255));

        btn_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/home_64.png"))); // NOI18N
        btn_Regresar.setMnemonic('R');
        btn_Regresar.setToolTipText("Regresar");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_Preprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Listo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Salir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_Bienvenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tb_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Preprar)
                    .addComponent(btn_Listo)
                    .addComponent(btn_Salir)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Regresar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btn_PreprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreprarActionPerformed
        //Boton para cambiar el color a la fila con una confirmacion
        try{
        String Estado = "Preparando";
        int Respuesta = JOptionPane.showConfirmDialog(null, "Confirmar?", "Mensaje!", JOptionPane.YES_NO_OPTION);
        if (Respuesta == JOptionPane.YES_OPTION) {
            tablacocina.setValueAt(Estado, tablacocina.getSelectedRow(), 3);
            tablacocina.setDefaultRenderer (Object.class, colorfilas);
            tablacocina.clearSelection();
        }
        else {
           JOptionPane.showMessageDialog(null, "Ha Cancelado la Accion");
            }
        }
        catch(Exception ex){
        }
    }//GEN-LAST:event_btn_PreprarActionPerformed

    private void btn_ListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListoActionPerformed
        //Boton para cambiar el color a la fila con una confirmacion
        try{
        String Estado = "Listo";
        int Respuesta = JOptionPane.showConfirmDialog(null, "Confirmar?", "Mensaje!", JOptionPane.YES_NO_OPTION);
        if (Respuesta == JOptionPane.YES_OPTION) {
            tablacocina.setValueAt(Estado, tablacocina.getSelectedRow(), 3);
            tablacocina.setDefaultRenderer (Object.class, colorfilas);
            tablacocina.clearSelection();
        }
        else {
           JOptionPane.showMessageDialog(null, "Ha Cancelado la Accion");
            }
        }
        catch(Exception ex){
        }
    }//GEN-LAST:event_btn_ListoActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        //Boton para salir del formulario cocina al formulario Acceso.
        try{
            this.setVisible(false); // Esconde el formulario.
            new frm_Acceso().setVisible(true);
            }
        catch (Exception ex){
        }
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        //Boton para realizar cambios o borrar despues que la orden esta lista.
        try{
            String [] Eleccion = {"Borrar", "Modificar"};
            String estado = "";
            Object opcion = JOptionPane.showInputDialog(null, "Selecciona una opcion:", "Elegir", JOptionPane.QUESTION_MESSAGE, null, Eleccion, Eleccion[0]);
                
             if ((opcion != null) && opcion.toString().equalsIgnoreCase("Borrar")){
                 cocina.removeRow(tablacocina.getSelectedRow());
             }
                else if ((opcion != null) && opcion.toString().equalsIgnoreCase("Modificar")){
                    tablacocina.setValueAt(estado, tablacocina.getSelectedRow(), 3);
                    tablacocina.setDefaultRenderer (Object.class, colorfilas);
             }
                else {
                    JOptionPane.showMessageDialog(null, "La accion ha sido cancelada");
                }
            }
        catch (Exception ex){
        }
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_Cocina().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Listo;
    private javax.swing.JButton btn_Preprar;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Bienvenido;
    public javax.swing.JLabel lbl_Mensaje;
    private javax.swing.JTable tablacocina;
    private javax.swing.JPanel tb_1;
    private javax.swing.JPanel tb_2;
    private javax.swing.JPanel tb_3;
    private javax.swing.JPanel tb_4;
    private javax.swing.JTabbedPane tb_Panel;
    // End of variables declaration//GEN-END:variables
}
