/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MerchantProyect;

//import LN.Producto;
import java.sql.Connection;
//import java.util.List;
import java.util.HashMap;
//import java.util.LinkedList;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author santiago
 */
public class frm_Reporte extends javax.swing.JFrame {

    /**
     * Creates new form frm_Reporte
     */
    public frm_Reporte() {
        initComponents();
    }

    /**
     *
     * @return
     */ 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Buscar = new javax.swing.JLabel();
        txt_Dia = new javax.swing.JTextField();
        btn_Generar = new javax.swing.JButton();
        txt_Mes = new javax.swing.JTextField();
        txt_Año = new javax.swing.JTextField();
        lbl_Dia = new javax.swing.JLabel();
        lbl_Mes = new javax.swing.JLabel();
        lbl_Año = new javax.swing.JLabel();
        tb_Panel = new javax.swing.JTabbedPane();
        tb_1 = new javax.swing.JPanel();
        btn_RPro = new javax.swing.JButton();
        btn_RUsu = new javax.swing.JButton();
        tb_2 = new javax.swing.JPanel();
        tb_3 = new javax.swing.JPanel();
        lbl_Bienvenido = new javax.swing.JLabel();
        lbl_Mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Merchant Reportes");
        setName("Reportes"); // NOI18N
        setResizable(false);

        lbl_Buscar.setText("Buscar Por:");

        btn_Generar.setText("Generar");

        lbl_Dia.setText("Dia:");

        lbl_Mes.setText("Mes:");

        lbl_Año.setText("Año:");

        btn_RPro.setText("Reporte Productos");
        btn_RPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RProActionPerformed(evt);
            }
        });

        btn_RUsu.setText("Reporte Usuarios");
        btn_RUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tb_1Layout = new javax.swing.GroupLayout(tb_1);
        tb_1.setLayout(tb_1Layout);
        tb_1Layout.setHorizontalGroup(
            tb_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_RPro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_RUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        tb_1Layout.setVerticalGroup(
            tb_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tb_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_RPro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        tb_Panel.addTab("Semanal", tb_1);

        javax.swing.GroupLayout tb_2Layout = new javax.swing.GroupLayout(tb_2);
        tb_2.setLayout(tb_2Layout);
        tb_2Layout.setHorizontalGroup(
            tb_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        tb_2Layout.setVerticalGroup(
            tb_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Mensual", tb_2);

        javax.swing.GroupLayout tb_3Layout = new javax.swing.GroupLayout(tb_3);
        tb_3.setLayout(tb_3Layout);
        tb_3Layout.setHorizontalGroup(
            tb_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );
        tb_3Layout.setVerticalGroup(
            tb_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Anual", tb_3);

        lbl_Bienvenido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Bienvenido.setText("Bienvenido:");

        lbl_Mensaje.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Mensaje.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb_Panel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Dia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Mes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Año)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Año, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Generar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Bienvenido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Buscar)
                        .addComponent(txt_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Generar)
                        .addComponent(txt_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Dia)
                        .addComponent(lbl_Mes)
                        .addComponent(lbl_Año))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(tb_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tb_Panel.getAccessibleContext().setAccessibleName("Tab");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RProActionPerformed
        Connection cn=MyConnection.getConnection();
        try{
          JasperReport jr = (JasperReport) JRLoader.loadObject(frm_Reporte.class.getResource("/Reportes/ReporteProductos.jasper"));
          //Codigo en comentario es agregando los datos directamente
          Map parametros = new HashMap<>();
          parametros.put("Titulo", "Reporte Productos");
          
            //List<Producto> obtenerProductos = obtenerProductos();
            //JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(obtenerProductos);
          
          
          //JasperPrint jp = JasperFillManager.fillReport(jr, parametros, ds);
          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp);
          jv.show(); 
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btn_RProActionPerformed

    private void btn_RUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RUsuActionPerformed

          Connection cn=MyConnection.getConnection();
          
        try{
          JasperReport jr = (JasperReport) JRLoader.loadObject(frm_Reporte.class.getResource("/Reportes/ReporteUsuarios.jasper"));
          //Codigo en comentario es agregando los datos directamente
          Map parametros = new HashMap<>();
          parametros.put("Titulo", "Reporte Usuarios");
          
            //List<Producto> obtenerProductos = obtenerProductos();
            //JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(obtenerProductos);
          
          
          //JasperPrint jp = JasperFillManager.fillReport(jr, parametros, ds);
          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp);
          jv.show(); 
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btn_RUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_Reporte().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Generar;
    private javax.swing.JButton btn_RPro;
    private javax.swing.JButton btn_RUsu;
    private javax.swing.JLabel lbl_Año;
    private javax.swing.JLabel lbl_Bienvenido;
    private javax.swing.JLabel lbl_Buscar;
    private javax.swing.JLabel lbl_Dia;
    public javax.swing.JLabel lbl_Mensaje;
    private javax.swing.JLabel lbl_Mes;
    private javax.swing.JPanel tb_1;
    private javax.swing.JPanel tb_2;
    private javax.swing.JPanel tb_3;
    private javax.swing.JTabbedPane tb_Panel;
    private javax.swing.JTextField txt_Año;
    private javax.swing.JTextField txt_Dia;
    private javax.swing.JTextField txt_Mes;
    // End of variables declaration//GEN-END:variables

//    public List<Producto> obtenerProductos(){
//
//        List res = new LinkedList();
//        //res.add(new Producto(1, "Cafe", 25, 1));
//        //res.add(new Producto(2, "Cafe con Leche", 30, 1));
//        //res.add(new Producto(3, "Cappucino", 35, 1));
//        
//        return res;
//    }
    
}
