/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MerchantProyect;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.util.Date;
import javax.swing.Timer;
/**
 *
 * @author santiago
 */
public class frm_Main extends javax.swing.JFrame {

    /**
     * Creates new form frm_Main
     */
    DefaultTableModel cafe;
    DefaultTableModel leche;
    
    public frm_Main() {
        initComponents();
        this.cafe = (DefaultTableModel) tablaprod.getModel();
        this.leche = (DefaultTableModel) tablafac.getModel();
        
        Mostrardatos("");
        MostrarHora();

    }

    public final void MostrarHora(){
        new Timer(100, (ActionEvent e) -> {
            lbl_Fecha.setText(new Date().toString());
        }).start();
    }
    
    public final void Comprobar(){
        // Funcion para comprobar los privilegios mediante el usuario.
        try{
        if (null != lbl_Mensaje.getText())switch (lbl_Mensaje.getText()) {
                case "Admin":
                    mn_Reg.setEnabled(true);
                    mn_Pro.setEnabled(true);
                    mn_Rep.setEnabled(true);
                    break;
                case "":
                    this.setVisible(false); // Esconde el formulario.
                    new frm_Acceso().setVisible(true);
                    break;
                default:
                    break;
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }   
    }
     public void RefrescarTabla(){
        cafe.setColumnCount(0);
        cafe.setRowCount(0);
        tablaprod.revalidate();
    }
    
    public final void Mostrardatos(String valor){
        //Funcion que llena la tabla producto.
        MyConnection cc=new MyConnection();
        Connection cn=MyConnection.getConnection();
        RefrescarTabla();
        cafe.addColumn("ID");
        cafe.addColumn("Producto");
        cafe.addColumn("Precio");
        cafe.addColumn("Cantidad");
        tablaprod.setModel(cafe);
        String sql;
        if (valor.equals(""))
        {
            sql="SELECT * FROM Producto";
        }
        else{
            sql="SELECT * FROM Producto WHERE (Producto='"+valor+"')";
        } 
 
            String []datos=new String [4];
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                        datos[2]=rs.getString(3);
                            datos[3]=rs.getString(4);
 
            cafe.addRow(datos);
        }
            tablaprod.setModel(cafe);
        }catch(SQLException ex){
            Logger.getLogger(frm_Productos.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */   
    
    public void MultiDialogo(){
        //Funcion Experimento de multiples input dentro de un Dialog.
        try {
            JTextField xField = new JTextField(5);
            JTextField yField = new JTextField(5);

            JPanel myPanel = new JPanel();
            myPanel.add(new JLabel("Tamaño:"));
            myPanel.add(xField);
            myPanel.add(Box.createHorizontalStrut(15)); // un espacio.
            myPanel.add(new JLabel("Cantidad:"));
            myPanel.add(yField);

            int result = JOptionPane.showConfirmDialog(null, myPanel, "Coloque el tamaño y la cantidad", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                System.out.println("tamaño: " + xField.getText());
                System.out.println("cantidad: " + yField.getText());
                }
            }
        catch (HeadlessException | NumberFormatException ex){
               JOptionPane.showMessageDialog(null, "error "+ex);
        }
    } 
    
    public void Dialogo(){
        //Funcion que presenta un mensaje con entrada para cambiar el valor de cantidad.
        try {
            String Regex = "^[0-9]+$"; // Variable para solo permitir estos valores dentro del input
            String resp = JOptionPane.showInputDialog(null, "Seleccione la cantidad que desea", "Cantidad", JOptionPane.OK_CANCEL_OPTION);
            if (Pattern.matches(Regex, resp) == true && (resp != null) && (resp.length() > 0)){
                    for(int i=0;i<tablaprod.getRowCount();++i){
                           tablaprod.setValueAt(resp,i,3); 
                        }
                    Seleccionar();
            }
                else if (resp == null) {
                JOptionPane.showMessageDialog(null, "Se ha Cancelado la accion");
                }
                else {
                JOptionPane.showMessageDialog(null, "Coloca un valor valido");    
                }
        }
        catch (HeadlessException | NumberFormatException | ArrayIndexOutOfBoundsException ex){
               JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    public void Seleccionar(){
        //Funcion que se encarga de pasar las filas de una tabla a otra.
        try {
            if(tablaprod.getSelectedRowCount() > 0) {
                // 1) Obtén los índices de las filas seleccionadas.
            int[] indices = tablaprod.getSelectedRows();
            // 2) Para cada fila, crea un Array para guardar los valores...
        for(int i : indices) {
            Object[] fila = new Object[cafe.getColumnCount()];
            // ... y guarda los valores de la fila de origen.
            for(int j = 0; j < fila.length; j++) {
                fila[j] = cafe.getValueAt(i, j);
            }
            // 3) Agrega la fila al TableModel de la tabla de destino
        leche.addRow(fila);
        CalculoTabla();
        tablaprod.clearSelection();
        Mostrardatos("");
        }
        }
        } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    public void CalculoTabla(){
        //Funcion para hacer los calculos del importe(cantidad x precio) y suma los resultados en el label total.
        try {
            int suma = 0, total;
        for(int i=0;i<tablafac.getRowCount();i++){
                int precio=Integer.parseInt(tablafac.getValueAt(i,2)+"");
                int cantidad=Integer.parseInt(tablafac.getValueAt(i,3)+"");
                    total = precio * cantidad;
                        tablafac.setValueAt(total, i, 4);
                    suma+=total;
                        lbl_Total.setText("$" + suma);
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablafac = new javax.swing.JTable();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_Monto = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        lbl_Mensaje = new javax.swing.JLabel();
        lbl_Bienvenido = new javax.swing.JLabel();
        tb_Panel = new javax.swing.JTabbedPane();
        tb_1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaprod = new javax.swing.JTable();
        tb_2 = new javax.swing.JPanel();
        tb_3 = new javax.swing.JPanel();
        tb_4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_Fecha = new javax.swing.JLabel();
        lbl_Mesas = new javax.swing.JLabel();
        menu_main = new javax.swing.JMenuBar();
        m_Arch = new javax.swing.JMenu();
        mn_Reg = new javax.swing.JMenuItem();
        mn_Pro = new javax.swing.JMenuItem();
        mn_Rep = new javax.swing.JMenuItem();
        mn_Imp = new javax.swing.JMenuItem();
        mn_Salir = new javax.swing.JMenuItem();
        m_Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Merchant POS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Main"); // NOI18N
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Actualizar(evt);
            }
        });

        tablafac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablafac.setName("Facturacion"); // NOI18N
        tablafac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Borrar(evt);
                TablaMulti(evt);
            }
        });
        jScrollPane2.setViewportView(tablafac);
        if (tablafac.getColumnModel().getColumnCount() > 0) {
            tablafac.getColumnModel().getColumn(0).setHeaderValue("ID");
        }

        lbl_Titulo.setFont(new java.awt.Font("SignPainter", 3, 36)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Titulo.setText("Merchant");

        lbl_Monto.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbl_Monto.setText("Monto:");

        lbl_Total.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbl_Total.setForeground(new java.awt.Color(51, 153, 0));

        lbl_Mensaje.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Mensaje.setForeground(new java.awt.Color(51, 51, 255));

        lbl_Bienvenido.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Bienvenido.setText("Bienvenido:");

        tablaprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaprod.setName("Producto"); // NOI18N
        tablaprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Seleccionar(evt);
            }
        });
        jScrollPane1.setViewportView(tablaprod);

        javax.swing.GroupLayout tb_1Layout = new javax.swing.GroupLayout(tb_1);
        tb_1.setLayout(tb_1Layout);
        tb_1Layout.setHorizontalGroup(
            tb_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        tb_1Layout.setVerticalGroup(
            tb_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        tb_Panel.addTab("Bebidas", tb_1);

        javax.swing.GroupLayout tb_2Layout = new javax.swing.GroupLayout(tb_2);
        tb_2.setLayout(tb_2Layout);
        tb_2Layout.setHorizontalGroup(
            tb_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tb_2Layout.setVerticalGroup(
            tb_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Aperitivos", tb_2);

        javax.swing.GroupLayout tb_3Layout = new javax.swing.GroupLayout(tb_3);
        tb_3.setLayout(tb_3Layout);
        tb_3Layout.setHorizontalGroup(
            tb_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tb_3Layout.setVerticalGroup(
            tb_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Comidas", tb_3);

        tb_4.setToolTipText("");

        javax.swing.GroupLayout tb_4Layout = new javax.swing.GroupLayout(tb_4);
        tb_4.setLayout(tb_4Layout);
        tb_4Layout.setHorizontalGroup(
            tb_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        tb_4Layout.setVerticalGroup(
            tb_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tb_Panel.addTab("Postres", null, tb_4, "");

        lbl_Fecha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_Fecha.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_Mesas.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbl_Mesas.setText("#");

        menu_main.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        m_Arch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/folder_16.png"))); // NOI18N
        m_Arch.setMnemonic('M');
        m_Arch.setText("Menu");
        m_Arch.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        mn_Reg.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        mn_Reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/address_16.png"))); // NOI18N
        mn_Reg.setMnemonic('R');
        mn_Reg.setText("Registro");
        mn_Reg.setEnabled(false);
        mn_Reg.setName(""); // NOI18N
        mn_Reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_RegActionPerformed(evt);
            }
        });
        m_Arch.add(mn_Reg);

        mn_Pro.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        mn_Pro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/buy_16.png"))); // NOI18N
        mn_Pro.setMnemonic('P');
        mn_Pro.setText("Productos");
        mn_Pro.setEnabled(false);
        mn_Pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ProActionPerformed(evt);
            }
        });
        m_Arch.add(mn_Pro);

        mn_Rep.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        mn_Rep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/diagram_16.png"))); // NOI18N
        mn_Rep.setMnemonic('E');
        mn_Rep.setText("Reportes");
        mn_Rep.setEnabled(false);
        mn_Rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_RepActionPerformed(evt);
            }
        });
        m_Arch.add(mn_Rep);

        mn_Imp.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        mn_Imp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/print_16.png"))); // NOI18N
        mn_Imp.setMnemonic('I');
        mn_Imp.setText("Imprimir");
        mn_Imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_ImpActionPerformed(evt);
            }
        });
        m_Arch.add(mn_Imp);

        mn_Salir.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        mn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/key_16.png"))); // NOI18N
        mn_Salir.setMnemonic('D');
        mn_Salir.setText("Desconectar");
        mn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_SalirActionPerformed(evt);
            }
        });
        m_Arch.add(mn_Salir);

        menu_main.add(m_Arch);

        m_Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/help_16.png"))); // NOI18N
        m_Ayuda.setMnemonic('A');
        m_Ayuda.setText("Ayuda");
        m_Ayuda.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        menu_main.add(m_Ayuda);

        setJMenuBar(menu_main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tb_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Bienvenido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Mesas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Monto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Titulo)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(tb_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Monto)
                        .addComponent(lbl_Mesas))
                    .addComponent(lbl_Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tb_Panel.getAccessibleContext().setAccessibleName("Menu");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Borrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Borrar
        //Este Evento borra o modifica al clickear sobre una fila de la tablafac.
        int Reseteo = 0;
        String [] Eleccion = {"Borrar", "Modificar"};
        String Regex = "^[0-9]+$"; //Variable para solo permitir estos valores dentro del input
         try{
             Object opcion = JOptionPane.showInputDialog(null, "Selecciona una opcion:", "Elegir", JOptionPane.QUESTION_MESSAGE, null, Eleccion, Eleccion[0]);
                
             if ((opcion != null) && opcion.toString().equalsIgnoreCase("Borrar")){
                 lbl_Total.setText("$" + Reseteo);
                 leche.removeRow(tablafac.getSelectedRow()); 
                    CalculoTabla();
                    tablafac.clearSelection();
             }
                else if ((opcion != null) && opcion.toString().equalsIgnoreCase("Modificar")){
                        String resp = JOptionPane.showInputDialog(null, "Seleccione la cantidad que desea", "Cantidad", JOptionPane.OK_CANCEL_OPTION);
                        if (Pattern.matches(Regex, resp) == true && (resp != null) && (resp.length() > 0)){
                        tablafac.setValueAt(resp,tablafac.getSelectedRow(),3);
                        tablafac.revalidate();
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "Coloca un valor valido");
                        }
             }
                else {
                    JOptionPane.showMessageDialog(null, "La accion ha sido cancelada");
                }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_Borrar

    private void Actualizar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Actualizar
        //Este evento utiliza la funcion calculo tabla cada vez que se mueve el mouse.
        try{
            CalculoTabla();
            Comprobar();
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_Actualizar

    private void mn_ImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ImpActionPerformed
        //Este boton imprime la tablafac completa.
     try {
            tablafac.print(); // Imprime el jTable.
        } 
        catch (PrinterException ex) { 
        JOptionPane.showMessageDialog(null, "error "+ex);
        }   
    }//GEN-LAST:event_mn_ImpActionPerformed

    private void mn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_SalirActionPerformed
        //Este boton abre el formulario Acceso y se despide con un mensaje.
        try{
        String Mensaje = lbl_Mensaje.getText();
            JOptionPane.showMessageDialog(null, "Adios "+Mensaje+" ");
            this.setVisible(false); // Esconde el formulario.
            new frm_Acceso().setVisible(true);
            }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_mn_SalirActionPerformed

    private void TablaMulti(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMulti
        //Evento moviendo el mouse que calcula los montos dentro de la tabla.
        try{
            CalculoTabla();
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_TablaMulti

    private void Seleccionar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seleccionar
        //Funcion que pide las cantidades y dentro la sub funcion Seleccionar
        Dialogo();   
    }//GEN-LAST:event_Seleccionar

    private void mn_ProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_ProActionPerformed
        //Este boton dentro del menu principal abre el formulario Productos.
        String usu = lbl_Mensaje.getText();
        try{
                    frm_Productos mf = new frm_Productos();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.lbl_Mensaje.setText(usu);
                    this.dispose();
                    }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_mn_ProActionPerformed

    private void mn_RegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_RegActionPerformed
        //Este boton dentro del menu principal abre el formulario Registro.
        String usu = lbl_Mensaje.getText();
        try{
                    frm_Registro mf = new frm_Registro();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.lbl_Mensaje.setText(usu);
                    this.dispose();
                    }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_mn_RegActionPerformed

    private void mn_RepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_RepActionPerformed
        //Este boton dentro del menu principal abre el formulario Reporte.
        String usu = lbl_Mensaje.getText();
        try{
                    frm_Reporte mf = new frm_Reporte();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.lbl_Mensaje.setText(usu);
                    this.dispose();
                    }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_mn_RepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_Main().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Bienvenido;
    private javax.swing.JLabel lbl_Fecha;
    public javax.swing.JLabel lbl_Mensaje;
    public javax.swing.JLabel lbl_Mesas;
    private javax.swing.JLabel lbl_Monto;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JMenu m_Arch;
    private javax.swing.JMenu m_Ayuda;
    private javax.swing.JMenuBar menu_main;
    private javax.swing.JMenuItem mn_Imp;
    private javax.swing.JMenuItem mn_Pro;
    private javax.swing.JMenuItem mn_Reg;
    private javax.swing.JMenuItem mn_Rep;
    private javax.swing.JMenuItem mn_Salir;
    private javax.swing.JTable tablafac;
    private javax.swing.JTable tablaprod;
    private javax.swing.JPanel tb_1;
    private javax.swing.JPanel tb_2;
    private javax.swing.JPanel tb_3;
    private javax.swing.JPanel tb_4;
    private javax.swing.JTabbedPane tb_Panel;
    // End of variables declaration//GEN-END:variables
}
