/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MerchantProyect;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author santiago
 */
public class frm_Acceso extends javax.swing.JFrame {

    /**
     * Creates new form frm_Acceso
     */
    public frm_Acceso() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param usuario
     * @return 
     */
    public boolean RevisarUsuario(String usuario) {
        //Funcion para revisar si el usuario existe dentro de la BD
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM `Usuario` WHERE `Usuario` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, usuario);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
         return checkUser;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Usuario = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        lbl_Contra = new javax.swing.JLabel();
        txtp_Contra = new javax.swing.JPasswordField();
        lbl_Letrero = new javax.swing.JLabel();
        lbl_Acceso = new javax.swing.JLabel();
        btn_Ingresar = new javax.swing.JButton();
        btn_Clave = new javax.swing.JButton();
        lbl_Olvido = new javax.swing.JLabel();
        lbl_Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Merchant Acceso");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Acceso"); // NOI18N
        setResizable(false);

        lbl_Usuario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Usuario.setText("Usuario:");

        txt_Usuario.setNextFocusableComponent(txtp_Contra);

        lbl_Contra.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_Contra.setText("Contraseña:");

        txtp_Contra.setNextFocusableComponent(btn_Ingresar);

        lbl_Letrero.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lbl_Letrero.setText("Merchant POS");

        lbl_Acceso.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbl_Acceso.setForeground(new java.awt.Color(51, 51, 255));
        lbl_Acceso.setText("Acceso");

        btn_Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/right_64.png"))); // NOI18N
        btn_Ingresar.setToolTipText("Ingresar");
        btn_Ingresar.setNextFocusableComponent(btn_Clave);
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });

        btn_Clave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/info_64.png"))); // NOI18N
        btn_Clave.setToolTipText("Recuperar Clave");
        btn_Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClaveActionPerformed(evt);
            }
        });

        lbl_Olvido.setText("Se te olvido tu contraseña?");

        lbl_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MerchantProyect/Icons/MerchantPOS.jpg"))); // NOI18N
        lbl_Imagen.setToolTipText("Merchant POS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(lbl_Acceso))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Contra, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_Usuario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Usuario)
                                .addComponent(txtp_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btn_Ingresar))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_Olvido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_Clave)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbl_Letrero)))
                .addGap(18, 18, 18)
                .addComponent(lbl_Imagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Letrero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Acceso)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_Usuario)
                                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_Contra)
                                    .addComponent(txtp_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_Ingresar))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Clave)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Olvido)
                                .addGap(26, 26, 26))))
                    .addComponent(lbl_Imagen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
        //Boton para acceder a la pantalla principal validando la informacion dentro de los text field y comprobandola con la BD
        PreparedStatement ps;
        ResultSet rs;
        String nom = txt_Usuario.getText();
        String cont = String.valueOf(txtp_Contra.getPassword());
        
        String query = "SELECT * FROM `Usuario` WHERE `Usuario` =? AND `Contraseña` =?";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, nom);
            ps.setString(2, cont);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                    frm_Mesas mf = new frm_Mesas();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.lbl_Mensaje.setText(nom);
                    
                    this.dispose();
            }
            else{
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrectos", "Fallo en Acesso", 2);
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(frm_Acceso.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void btn_ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClaveActionPerformed
        //Boton para dar informacion al usuario si olvida su contraseña
        JOptionPane.showMessageDialog(null, "Porfavor contactar con su supervisor");
    }//GEN-LAST:event_btn_ClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_Acceso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clave;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JLabel lbl_Acceso;
    private javax.swing.JLabel lbl_Contra;
    private javax.swing.JLabel lbl_Imagen;
    private javax.swing.JLabel lbl_Letrero;
    private javax.swing.JLabel lbl_Olvido;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JTextField txt_Usuario;
    private javax.swing.JPasswordField txtp_Contra;
    // End of variables declaration//GEN-END:variables
}
